server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/application.log

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
