server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/application.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
